[2024-11-20T04:02:01.168+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T04:02:01.220+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: university_ranking_etl.extract manual__2024-11-20T04:01:21.162234+00:00 [queued]>
[2024-11-20T04:02:01.248+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: university_ranking_etl.extract manual__2024-11-20T04:01:21.162234+00:00 [queued]>
[2024-11-20T04:02:01.249+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-20T04:02:01.276+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-11-20 04:01:21.162234+00:00
[2024-11-20T04:02:01.290+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T04:02:01.292+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2024-11-20T04:02:01.295+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'university_ranking_etl', 'extract', 'manual__2024-11-20T04:01:21.162234+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/etl_***.py', '--cfg-path', '/tmp/tmp12e_31cg']
[2024-11-20T04:02:01.297+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask extract
[2024-11-20T04:02:01.439+0000] {task_command.py:467} INFO - Running <TaskInstance: university_ranking_etl.extract manual__2024-11-20T04:01:21.162234+00:00 [running]> on host 03564abddc6d
[2024-11-20T04:02:06.320+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='university_ranking_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T04:01:21.162234+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T04:01:21.162234+00:00'
[2024-11-20T04:02:06.322+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T04:02:06.323+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T04:02:06.324+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-11-20 04:02:01.222764+00:00
[2024-11-20T04:02:06.324+0000] {logging_mixin.py:190} INFO - Dag name:university_ranking_etl and current dag run status:running
[2024-11-20T04:02:06.325+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T04:02:06.327+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-11-20T04:02:06.435+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:02:06.675+0000] {logger.py:11} INFO - Getting latest mozilla release info for v0.35.0
[2024-11-20T04:02:07.153+0000] {logger.py:11} INFO - About to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
[2024-11-20T04:02:09.319+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-11-20T04:02:10.155+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:02:10.433+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:02:10.695+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/geckodriver/linux64/v0.35.0]
[2024-11-20T04:02:10.785+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 15, in extract
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[2024-11-20T04:02:10.815+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T04:02:10.815+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 04:02:01.222764+00:00 end:2024-11-20 04:02:10.814611+00:00 duration:9.591847
[2024-11-20T04:02:10.816+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: university_ranking_etl> dagrun:<DagRun university_ranking_etl @ 2024-11-20 04:01:21.162234+00:00: manual__2024-11-20T04:01:21.162234+00:00, state:running, queued_at: 2024-11-20 04:01:21.229311+00:00. externally triggered: True>
[2024-11-20T04:02:10.816+0000] {logging_mixin.py:190} INFO - Failure caused by Message: binary is not a Firefox executable
[2024-11-20T04:02:10.817+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=university_ranking_etl, task_id=extract, run_id=manual__2024-11-20T04:01:21.162234+00:00, execution_date=20241120T040121, start_date=20241120T040201, end_date=20241120T040210
[2024-11-20T04:02:10.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T04:02:10.846+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task extract (Message: binary is not a Firefox executable
; 103)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 15, in extract
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[2024-11-20T04:02:10.895+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T04:02:11.211+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T04:02:11.215+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
