[2024-11-20T04:07:17.550+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T04:07:17.577+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: university_ranking_etl.extract scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2024-11-20T04:07:17.589+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: university_ranking_etl.extract scheduled__2024-11-19T00:00:00+00:00 [queued]>
[2024-11-20T04:07:17.590+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-20T04:07:17.608+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract> on 2024-11-19 00:00:00+00:00
[2024-11-20T04:07:17.620+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T04:07:17.622+0000] {standard_task_runner.py:72} INFO - Started process 243 to run task
[2024-11-20T04:07:17.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'university_ranking_etl', 'extract', 'scheduled__2024-11-19T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_***.py', '--cfg-path', '/tmp/tmp8g2k3hlc']
[2024-11-20T04:07:17.625+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask extract
[2024-11-20T04:07:17.697+0000] {task_command.py:467} INFO - Running <TaskInstance: university_ranking_etl.extract scheduled__2024-11-19T00:00:00+00:00 [running]> on host 03564abddc6d
[2024-11-20T04:07:20.307+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='university_ranking_etl' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T00:00:00+00:00'
[2024-11-20T04:07:20.309+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T04:07:20.309+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T04:07:20.310+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2024-11-20 04:07:17.577918+00:00
[2024-11-20T04:07:20.310+0000] {logging_mixin.py:190} INFO - Dag name:university_ranking_etl and current dag run status:running
[2024-11-20T04:07:20.311+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T04:07:20.312+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-11-20T04:07:20.329+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:07:20.824+0000] {logger.py:11} INFO - Getting latest mozilla release info for v0.35.0
[2024-11-20T04:07:21.322+0000] {logger.py:11} INFO - About to download new driver from https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
[2024-11-20T04:07:23.266+0000] {logger.py:11} INFO - Driver downloading response is 200
[2024-11-20T04:07:23.896+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:07:24.376+0000] {logger.py:11} INFO - Get LATEST geckodriver version for None firefox
[2024-11-20T04:07:24.559+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/geckodriver/linux64/v0.35.0]
[2024-11-20T04:07:24.629+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 15, in extract
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[2024-11-20T04:07:24.680+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T04:07:24.681+0000] {logging_mixin.py:190} INFO - Task start:2024-11-20 04:07:17.577918+00:00 end:2024-11-20 04:07:24.679774+00:00 duration:7.101856
[2024-11-20T04:07:24.681+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: university_ranking_etl> dagrun:<DagRun university_ranking_etl @ 2024-11-19 00:00:00+00:00: scheduled__2024-11-19T00:00:00+00:00, state:running, queued_at: 2024-11-20 04:01:14.292156+00:00. externally triggered: False>
[2024-11-20T04:07:24.682+0000] {logging_mixin.py:190} INFO - Failure caused by Message: binary is not a Firefox executable
[2024-11-20T04:07:24.682+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=university_ranking_etl, task_id=extract, run_id=scheduled__2024-11-19T00:00:00+00:00, execution_date=20241119T000000, start_date=20241120T040717, end_date=20241120T040724
[2024-11-20T04:07:24.711+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T04:07:24.712+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task extract (Message: binary is not a Firefox executable
; 243)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_airflow.py", line 15, in extract
    driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: binary is not a Firefox executable

[2024-11-20T04:07:24.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T04:07:25.102+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T04:07:25.109+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
